#!/usr/bin/env python
# encoding: utf-8

def build(ctx):
  ctx.program(
      source = [
          'main.cc',
          ],
      target = '../dcpu',
      includes = [
        '.',
        ],
      use = [
        ],
      cxxflags = [
        '-g',
        ])
