#!/usr/bin/env python
# encoding: utf-8

def build(ctx):
  ctx.stlib(
      source = [
        'assembler.cc',
        'dcpu.cc',
        'disassembler.cc',
        'program.pb.cc',
        ],
      target = 'dcpu',
      includes = [
        '.',
        '../libraries/protobuf-2.4.1/src',
        ],
      use = [
        'NCURSES',
        'protobuf',
        ],
      cxxflags = [
        '-g',
        ])
  ctx.objects(
      source = [
        'dcpu_test.cc',
        'disassembler_test.cc',
        ],
      target = 'dcpu_tests',
      includes = [
        '../libraries/gtest-1.6.0/include',
        '.',
        ],
      use = [
        'dcpu',
        'gtest',
        ])
  ctx.program(
      source = [
        'main.cc',
        ],
      target = '../dcpu',
      includes = [
        '.',
        '../libraries/protobuf-2.4.1/src',
        ],
      use = [
        'dcpu',
        ],
      cxxflags = [
        '-g',
        ])
